Modernize
savaslabs/savas-slack-tools pull request #14
Opened 2021-05-31 17:43 UTC by sposhe

**Updates:**

- Splits directives and shared functions into discrete javascript modules
- Modernizes javascript
- Adds `teams` directive
- Changes `conf/conf.js` to `conf/conf.json` to avoid use of `eval()`

**Testing:** 

Note that this changes the configuration file from a javascript file to a JSON file, so your local configuration file will need to be changed to JSON.

Please test that each directive works as outlined in the README. (Note that to avoid pinging the team when testing `/savbot savasclaus`, the slack ID in `/js/savasclaus.js` should be set to your slack ID)

**Deployment:**

The configuration file on the server will also need to be changed to JSON.

2021-08-16 14:54 UTC, maddybvh commented
Hi @sposhe , amazing work on this! 💪  👏   Everything works just as described.

I left a couple of code comments where I think the documentation could be more clear. In addition to those, I'd suggest we do the following for consistency with our other Node/JS work:
- Add `nodemon` for hot reloading
- Add style config files from our [JS Standards](https://github.com/savaslabs/js-standards) repo
- Save env variables as env variables, unless there's a compelling reason not to

If that all sounds good to you, I'm happy to push up those changes and pass this over to @dmurphy1 for deployment.

2021-08-16 15:46 UTC, maddybvh requested changes
Please see code comments!

2021-08-16 15:47 UTC, sposhe commented on conf/conf.example.json
> +  "team": [
It can be removed!

2021-08-16 15:49 UTC, sposhe commented on conf/conf.example.json
> +  "token": "[String provided by Slack]",
Just that that was how it was initially set up, and I don't have enough node experience to have used a `.env` file much!

2021-08-16 15:50 UTC, sposhe commented on README.md
> +Duplicate `conf.example.json` as `conf.json` and add the Slack secret token from the Slack command configuration page (https://savaslabs.slack.com/services/B22JGF3GU). This is also where you would ad
Agreed.

2021-08-16 15:52 UTC, sposhe commented
All suggestions sound great, thanks!

2021-08-17 16:05 UTC, maddybvh approved these changes
Hi @dmurphy1 , I pushed up changes to address the change requests documented above, specifically:
- Adding `nodemon`
- Adding linting
- Converting `conf` to `.env` and accessing via `dotenv`.
- Updating documentation

Passing this over to you for a secondary review if you have time, or just to merge and deploy.

Note that during deployment, you'll need to set the env variables on production.

2021-08-17 19:04 UTC, dmurphy1 commented
LGTM, merging!

2021-08-17 19:04 UTC, merged